# Generated by Django 5.2.7 on 2025-10-27 10:10

import muco_django.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to=muco_django.utils.UploadByFieldCount('brief'))),
                ('vision', models.CharField(max_length=700)),
                ('asked_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ai_score', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
