# Generated by Django 5.2.7 on 2025-10-27 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bid_app', '0001_initial'),
        ('brief_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='brief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brief_app.brief'),
        ),
    ]
