# Generated by Django 5.2.7 on 2025-10-27 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefimage',
            name='brief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='brief_app.brief'),
        ),
    ]
