# Generated by Django 5.2.7 on 2025-11-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_app', '0003_alter_briefimage_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
