# Generated by Django 5.2.7 on 2025-10-28 17:30

import muco_django.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=muco_django.utils.UploadByField('name')),
        ),
    ]
