# Generated by Django 5.2.7 on 2025-10-30 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brief_app', '0003_alter_briefimage_brief'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='')),
                ('completed', models.BooleanField(default=False)),
                ('brief', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brief_app.brief')),
            ],
        ),
    ]
