# Generated by Django 5.2.7 on 2025-10-30 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0003_initial'),
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='video',
        ),
        migrations.AddField(
            model_name='order',
            name='bid',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='bid_app.bid'),
            preserve_default=False,
        ),
    ]
