# Generated by Django 5.2.7 on 2025-11-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_remove_order_video_order_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
